# Generated by Django 5.0 on 2024-03-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_job_seeker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.city')),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('openings', models.IntegerField()),
                ('stipend', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.city')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.job_fields')),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.hr')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.job')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.status')),
            ],
        ),
    ]
