# Generated by Django 5.0 on 2024-04-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_status_hr_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_rqd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.skill')),
            ],
        ),
    ]
