# Generated by Django 5.0 on 2024-04-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_skill_rqd'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=250)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.job')),
            ],
        ),
    ]
